name: Log Messages 5 Times

# Triggered manually using workflow_dispatch event
on:
  workflow_dispatch: # This event allows the workflow to be triggered manually

jobs:
  log-messages:
    runs-on: ubuntu-latest # Specify the OS environment for the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # This step checks out the repository code (if needed)

      - name: Log message 1
        run: echo "Log" #1: Hello, this is message number 1!"  # Logs message 1

      - name: Log message 2
        run: echo "Log" #2: Hello, this is message number 2!"  # Logs message 2

      - name: Log message 3
        run: echo "Log" #3: Hello, this is message number 3!"  # Logs message 3

      - name: Log message 4
        run: echo "Log" #4: Hello, this is message number 4!"  # Logs message 4
